/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { useEffect, useRef, useState } from 'react';
import { Box3, Group, Vector3 } from 'three';

export function Rack({ targetSize,...props}) {
    const localRef = useRef<Group>(null);
    const { nodes, materials, scene } = useGLTF('/models/Rack_Processed.glb')
    const [scaleVec, setScaleVec] = useState(() => new Vector3(1, 1, 1));

    useEffect(() => {
        if (!scene) return;

        const bbox = new Box3().setFromObject(scene);
        const size = new Vector3();
        bbox.getSize(size);
        
        setScaleVec(new Vector3(
            targetSize[0] / size.x,
            targetSize[1] / 20,
            targetSize[2] / size.z
        ));
    }, [targetSize, scene]);

    return (
        <group  dispose={null}>
            <group ref={localRef} scale={scaleVec} {...props}>
                <group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh1__1_0.geometry}
                        material={materials.material}
                        position={[-0.602, -2.612, 7.949]}
                        scale={[0.98, 1, 1]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh1__2_0.geometry}
                        material={materials.material_3}
                        position={[-0.061, 1.98, 8.499]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh1__3_0.geometry}
                        material={materials.material_2}
                        position={[-0.061, 0.33, -7.106]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh1_Wood_Plywood_Knots_0.geometry}
                        material={materials.Wood_Plywood_Knots}
                        position={[0.724, 0.303, -9.343]}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/Rack_Processed.glb');