/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Asset } from "expo-asset";
import { useEffect, useRef, useState } from 'react';
import { Box3, Group, Vector3 } from 'three';
import { GLTFLoader } from "three-stdlib";

export function Rackmobile({ targetSize,pos,...props}) {
    const localRef = useRef<Group>(null);
    //const { nodes, materials, scene } = useGLTF(require('../../assets/models/Table_processed.glb'))
    const [gltf, setGltf] = useState(null);
    const [scaleVec, setScaleVec] = useState(() => new Vector3(1, 1, 1));

    useEffect(() => {
        const load = async () => {
            // Resolve the local .glb file
            const asset = Asset.fromModule(require("../../assets/models/Rack_Processed.glb"));
            await asset.downloadAsync();
            
            // Load into three.js scene
            const loader = new GLTFLoader();
            loader.load(
                asset.localUri || asset.uri,
                (gltf) => setGltf(gltf),
                undefined,
                (error) => console.error("GLB load error:", error)
            );
        };
        load();
    }, []);
    useEffect(() => {
        if(gltf){
            const bbox = new Box3().setFromObject(gltf.scene);
            const size = new Vector3();
            bbox.getSize(size);
            //targetSize = [targetSize[0] * 10, targetSize[1], targetSize[2] * 10];
            pos = new Vector3(pos.x, 0, pos.z);
            setScaleVec(new Vector3(
                targetSize[0],
                targetSize[1] / 2,
                targetSize[2] / 3.5
            ));
        }
    },[gltf])

    if(!gltf) return null;
    return (
        <primitive object={gltf.scene} scale={scaleVec} {...props}  position={[pos.x,0,pos.z]} />
        /*<group ref={localRef} {...props} position={pos.toArray()}>
            <mesh >
                <boxGeometry args={targetSize} />
                <meshStandardMaterial color='orange'/>
            </mesh>
        </group>*/
        /*<group ref={localRef} {...props} scale={50} dispose={null}>
        <mesh castShadow receiveShadow geometry={nodes.Plate.geometry}  />
        <mesh 
            castShadow
            receiveShadow
            geometry={nodes.Legs01Left.geometry}
            material={materials.Metal}
            position={[-1.5, 0, 0]}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Legs01Right.geometry}
            material={materials.Metal}
            position={[1.5, 0, 0]}
        />
        </group>*/
    )
}