/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { useEffect, useRef, useState } from 'react';
import { Box3, Group, Vector3 } from 'three';
import { TableGrid } from './TableGrid';

export function Table({ targetSize,product,...props}) {
    const localRef = useRef<Group>(null);
    const { nodes, materials, scene } = useGLTF('/models/Table.gltf');
    const [scaleVec, setScaleVec] = useState(() => new Vector3(1, 1, 1));

    useEffect(() => {
        if (!scene) return;

        const bbox = new Box3().setFromObject(scene);
        const size = new Vector3();
        bbox.getSize(size);

        setScaleVec(new Vector3(
            targetSize[0] / size.x,
            targetSize[1] / 2,
            targetSize[2] / size.z
        ));
    }, [targetSize, scene]);

    return (
        <group>
            <group ref={localRef} scale={scaleVec} {...props} dispose={null}>
                <TableGrid product={product} scale={[1 / scaleVec.x, 1 / scaleVec.y, 1 / scaleVec.z]} />
                <mesh castShadow receiveShadow geometry={nodes.Plate.geometry} material={materials.Plate}  />
                <mesh 
                    castShadow
                    receiveShadow
                    geometry={nodes.Legs01Left.geometry}
                    material={materials.Metal}
                    position={[-1.5, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Legs01Right.geometry}
                    material={materials.Metal}
                    position={[1.5, 0, 0]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/Table.gltf');
